# Generated by Django 6.0.5 on 2026-05-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.CharField(choices=[('AIIMS', 'All India Institute of Medical Sciences (AIIMS)'), ('Safdarjung', 'Safdarjung Hospital'), ('RML', 'Ram Manohar Lohia Hospital'), ('LNJP', 'Lok Nayak Jai Prakash Narayan Hospital'), ('GTB', 'Guru Teg Bahadur Hospital'), ('DDU', 'Deen Dayal Upadhyay Hospital'), ('Apollo', 'Indraprastha Apollo Hospital | Best Hospital in Delhi'), ('BLK_Max', 'BLK-Max Super Speciality Hospital Delhi'), ('Max_Saket', 'Max Super Speciality Hospital, Saket (Max Saket)'), ('Max_Smart', 'Max Smart Super Speciality Hospital, Saket (Max Smart)'), ('Fortis_VK', 'Fortis Flt Lt Rajan Dhall Hospital, Vasant Kunj - Best Hospital in New Delhi'), ('Fortis_SB', 'Fortis Hospital, Shalimar Bagh - Best Hospital in New Delhi'), ('Narayana', 'Dharamshila Narayana Superspeciality Hospital, Delhi')], default='AIIMS', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('General Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospital',
            field=models.CharField(blank=True, choices=[('AIIMS', 'All India Institute of Medical Sciences (AIIMS)'), ('Safdarjung', 'Safdarjung Hospital'), ('RML', 'Ram Manohar Lohia Hospital'), ('LNJP', 'Lok Nayak Jai Prakash Narayan Hospital'), ('GTB', 'Guru Teg Bahadur Hospital'), ('DDU', 'Deen Dayal Upadhyay Hospital'), ('Apollo', 'Indraprastha Apollo Hospital | Best Hospital in Delhi'), ('BLK_Max', 'BLK-Max Super Speciality Hospital Delhi'), ('Max_Saket', 'Max Super Speciality Hospital, Saket (Max Saket)'), ('Max_Smart', 'Max Smart Super Speciality Hospital, Saket (Max Smart)'), ('Fortis_VK', 'Fortis Flt Lt Rajan Dhall Hospital, Vasant Kunj - Best Hospital in New Delhi'), ('Fortis_SB', 'Fortis Hospital, Shalimar Bagh - Best Hospital in New Delhi'), ('Narayana', 'Dharamshila Narayana Superspeciality Hospital, Delhi')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=10),
        ),
    ]
