# Generated by Django 6.0.5 on 2026-05-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresync', '0002_appointment_hospital_profile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
