# Generated by Django 6.0.5 on 2026-05-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresync', '0003_helpticket_admin_response_profile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
