# Generated by Django 6.0.5 on 2026-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresync', '0004_medicalrecord_doctor_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='user_ticket_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
